export default {
    data() {
        return {
            productItemss: [
                {
                    id: 1,
                    productImage: '/img/products/product-thumb-01.png',
                    productTitle: 'Turn Yourself',
                    productPrice: '$24.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fal fa-star',
                },
                {
                    id: 2,
                    productImage: '/img/products/product-thumb-02.png',
                    productTitle: 'Art of Not Giving',
                    productPrice: '$12.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fal fa-star',
                    productRating5: 'fal fa-star',
                },
                {
                    id: 3,
                    productImage: '/img/products/product-thumb-03.png',
                    productTitle: 'Attract Women',
                    productPrice: '$24.00',
                    productOldPrice: '$45.50',
                    productOldPriceClass: 'shop-old-price',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fal fa-star',
                    productRating4: 'fal fa-star',
                    productRating5: 'fal fa-star',
                },
                {
                    id: 4,
                    productImage: '/img/products/product-thumb-04.png',
                    productTitle: 'Think and Grow Rich',
                    productPrice: '$16.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fal fa-star',
                },
                {
                    id: 5,
                    productImage: '/img/products/product-thumb-05.png',
                    productTitle: 'Best Inspirational',
                    productPrice: '$22.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 6,
                    productImage: '/img/products/product-thumb-06.png',
                    productTitle: 'The Power of Evil',
                    productPrice: '$17.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 7,
                    productImage: '/img/products/product-thumb-07.png',
                    productTitle: 'Practical Strees',
                    productPrice: '$23.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 8,
                    productImage: '/img/products/product-thumb-08.png',
                    productTitle: 'Memoirs of a Geisha',
                    productPrice: '$28.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 9,
                    productImage: '/img/products/product-thumb-09.png',
                    productTitle: 'Very First Sight',
                    productPrice: '$25.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 10,
                    productImage: '/img/products/product-thumb-10.png',
                    productTitle: 'The Almanack',
                    productPrice: '$19.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 11,
                    productImage: '/img/products/product-thumb-11.png',
                    productTitle: 'Wealth & Happiness',
                    productPrice: '$24.00',
                    productOldPrice: '$75.00',
                    productOldPriceClass: 'shop-old-price',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fal fa-star',
                },
                {
                    id: 12,
                    productImage: '/img/products/product-thumb-12.png',
                    productTitle: 'Rabbit drawing book',
                    productPrice: '$23.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 13,
                    productImage: '/img/products/product-thumb-13.png',
                    productTitle: 'Time Management',
                    productPrice: '$32.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 14,
                    productImage: '/img/products/product-thumb-14.png',
                    productTitle: 'Startup Dream',
                    productPrice: '$29.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 15,
                    productImage: '/img/products/product-thumb-15.png',
                    productTitle: 'Positive Attitude',
                    productPrice: '$75.00',
                    productOldPrice: '$92.00',
                    productOldPriceClass: 'shop-old-price',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                },
                {
                    id: 16,
                    productImage: '/img/products/product-thumb-01.png',
                    productTitle: 'Options Handboo',
                    productPrice: '$11.00',
                    productOldPrice: '',
                    productOldPriceClass: 'shop-old-price d-none',
                    productRating1: 'fas fa-star',
                    productRating2: 'fas fa-star',
                    productRating3: 'fas fa-star',
                    productRating4: 'fas fa-star',
                    productRating5: 'fas fa-star',
                }
            ]
        }
    }
}